name: Deploy Sphinx Docs to Pages

on:
  # Runs on pushes targeting the main branch
  push:
    branches: ["main", "master"]  # Change this to "main" or your default branch

  pull_request:
    branches: [ "main" ]  # Runs on pull requests targeting the main branch

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However,  do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Create .nojekyll file before anything else to disable Jekyll
      - name: Disable Jekyll
        run: touch .nojekyll

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r docs/requirements.txt
          pip install sphinx sphinx_rtd_theme sphinx_copybutton

      # - name: Build Sphinx docs
      #   run: |
      #     cd docs
      #     make html
      #     # Debug output
      #     ls -la _build/html/
      #     # Add .nojekyll file to tell GitHub not to use Jekyll
      #     touch _build/html/.nojekyll

      - name: Build Sphinx documentation manually
        run: |
          cd docs
          sphinx-build -b html . _build/html
          # Debug output
          ls -la _build/html/
          # Verify index.html exists
          test -f _build/html/index.html || { echo "ERROR: index.html not found!"; exit 1; }
          # Add .nojekyll file to build output
          cp ../.nojekyll _build/html/

      # - name: Setup Pages
      #   uses: actions/configure-pages@v4
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'docs/_build/html'
  
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
